phrase:
  access_token: 7094ccbfb01e6d93c4fafd6d1fb8023ee90b3ad8aae03e9110cff86cbe6ce067
  project_id: cdf7eaf8a2990628a2bac4f6e1d76094
  push:
    sources:
    - file: ./locales/en.json
      params:
        file_format: simple_json
        update_translations: true
        locale_id: bc0aaca0a532eb19ca55fdf1d4045c2e
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: simple_json
